os:
  - linux
language: java
jdk:
  - openjdk8
  - openjdk11 # the build should work also with JDK 11.
script:
  - set -e
  - mvn clean install -Pcheckstyle -PtestCoverage jacoco:report coveralls:report
